flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- hslua-1.3.0
- hslua-module-path-0.1.0
- jira-wiki-markup-1.3.4
- skylighting-core-0.10.5.1
- skylighting-0.10.5.1
- doclayout-0.3.0.2
- texmath-0.12.2
- random-1.2.0
# - citeproc-0.3.0.9
- git: https://github.com/jgm/citeproc
  commit: 9f638790288c8661a17fa2d982ad66348a3c874f
- git: https://github.com/jgm/unicode-collation
  commit: 00f5e8c90774b20e1185a8c1e81856049e743db6
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-17.5
nix:
  packages: [zlib]
